Отрезание старой инфы
Jymapas/WeekChgkSPBParser pull request #13
Opened 2022-11-01 14:14 UTC by Jymapas

Реализовал отрезание старой инфы для варианта с .txt

2022-11-02 07:45 UTC, FA72 requested changes
Ну такое. Будто забыл некоторые вещи снова. Подумай получше, где я комменты оставил

2022-11-02 07:45 UTC, FA72 commented on WeekChgkSPBParser/Constants/Paths.cs
> +    internal record Paths
Всё ещё не уверен, что всё это должно быть record. Кажется, достаточно, если константы будут просто class, но тут я уточню у коллег как-нибудь

2022-11-02 07:45 UTC, FA72 commented on WeekChgkSPBParser/Helpers/GetFromTxtHelper.cs
> +            return File.ReadAllLines(path);
А для этого точно нужен отдельный метод? Но ладно

2022-11-02 07:45 UTC, FA72 commented on WeekChgkSPBParser/API/Exist.cs
> +        private static bool _exist = true;
Да ещё и с тем же названием, что и класс. Ну Саш. Ну бля. Ну Саш

2022-11-02 07:49 UTC, Jymapas commented on WeekChgkSPBParser/Helpers/GetFromTxtHelper.cs
> +            return File.ReadAllLines(path);
Ну а как? Читать из файла в одну строку в методе, а читать из фала по линиям прямо на месте? Думаю, что все читалки из файла хранить в одном месте лучше.

2022-11-02 07:56 UTC, FA72 commented on WeekChgkSPBParser/Helpers/GetFromTxtHelper.cs
> +            return File.ReadAllLines(path);
Ок-ок, я не против в целом

2022-11-02 07:59 UTC, Jymapas commented on WeekChgkSPBParser/API/Announcement.cs
> +            return string.Join("\n", clearLines);
Логика такая:
Пока `!tooOld` я проверяю, является день старым. Когда нахожу сегодня или познее, то дальше `tooOld = false` и больше эти проверки я не делаю, а просто добавляю все строки подряд.

2022-11-02 11:43 UTC, Jymapas commented on WeekChgkSPBParser/Constants/Paths.cs
> +    internal record Paths
Окей, я верну в классы вместо рекордов. Потом будет интересно узнать, как вообще на это смотрят умные люди.

2022-12-06 06:59 UTC, FA72 approved these changes

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/API/FilesExist.cs
> +    public class FilesExist
Название классов - существительные

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/API/GetAnnouncement.cs
> +    internal class GetAnnouncement
Название класса - существительное

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/API/GetAnnouncement.cs
> +        private DateOnly _today = DateOnly.FromDateTime(DateTime.Now);
Не используется

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/API/GetAnnouncement.cs
> +            var today = DateOnly.FromDateTime(DateTime.Today);
Вместо этого используй поле

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/API/GetAnnouncement.cs
> +        private static string ClearOldInfo(string[] lines, DateOnly today)
Если использовать поле, вместо локальной переменной, то даже ничего передавать не надо дальше

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/API/GetAnnouncement.cs
> +        private static bool ShouldSkip(string line, DateOnly today, CultureInfo ruCulture)
То же самое. Тудей тогда не передаётся и выдёргивается поле на месте

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/API/GetAnnouncement.cs
> +            return date < today;
Но вообще это единственное место в классе, где используется тудей. Соответственно и поле не нужно и передавать внутрь так дофига смысла нет. Здесь на месте сравнивай
`date < DateOnly.FromDateTime(DateTime.Now)`

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/Readers/LjPostReader.cs
> +            if (txt == null)
var txt = GetSource(Paths.LjUrl) ?? string.Empty;

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/Readers/LjPostReader.cs
> +                return null;
Вообще, по-хорошему делать не так, а здесь ты должен выбрасывать кастомное исключение (например, AnnounceEmptyException) и в GetAnnounce не проверять на нуль, а тоже делать try с кетчем этой ошибки и, следовательно, там уже обрабатывать её выбрасыванием String.Empty

2022-12-06 06:59 UTC, FA72 commented on WeekChgkSPBParser/Readers/TxtPostReader.cs
> +            GetAnnouncement getAnnouncement = new(lines);
переменная тоже должна быть существительным

2023-11-09 13:28 UTC, merged