feature/4_fromTxt
Jymapas/WeekChgkSPBParser pull request #5
Opened 2022-10-05 14:32 UTC by Jymapas

Тупо рыбу сделал, чтобы понять, как делать ПР.
Всё равно, вероятно, что-то не то сделал.

2022-10-06 14:25 UTC, FA72 requested changes
Пока по кодстайлу дофига косяков

2022-10-07 10:02 UTC, Jymapas commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +        }
Погоди, то есть `public string Announcement { get; priveta set; }` будет работать так же?

2022-10-07 10:05 UTC, Jymapas commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +        internal static string TgFormat(StreamReader sr)
Видимо, осталась с момента теста идеи. Убрал, конечно.

2022-10-07 10:07 UTC, Jymapas commented on WeekChgkSPBParser/API/TxtPost.cs
> +            using (StreamReader streamReader = file.OpenText())
Да, согласен, что симпатичнее. Поправил.

2022-10-07 10:09 UTC, Jymapas commented on WeekChgkSPBParser/Constants.cs
>      {
Тогда это будет 3 или 4 разных класса, каждый из которых для одной или двух констант. Поправлю уже в другой ветке.

2022-10-07 11:22 UTC, Jymapas commented on WeekChgkSPBParser/Constants.cs
>          internal const string TgToken = $"";
Да, я понимаю.
Сделаю это отдельно, иссью для этого сделал.

2022-10-07 11:23 UTC, Jymapas commented on WeekChgkSPBParser/API/LjPost.cs
> +        string post = GetPost();
Здесь и ниже поправил.

2022-10-07 11:45 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +        }
Да

2022-10-07 12:25 UTC, FA72 commented on WeekChgkSPBParser/API/Connect.cs
>          internal ITelegramBotClient Bot = new TelegramBotClient(Constants.TgToken);
А он снаружи где-то используется? 
Поля должны быть либо private, либо private protection. Старайся избегать других. 
internal я практически не использую. Но это не ошибка.
Сделай из поля автосвойство (прост {get;set;} можешь добавить и тогда инициализацию лучше в конструктор вынести)

2022-10-07 12:25 UTC, FA72 commented on WeekChgkSPBParser/API/LjPost.cs
> +        private string _post = GetPost();
Мне не нравится такая реализация. Вообще лучше при инициализации полей методы не вызывать. Если хочешь использовать так, сделай конструктор. Я бы вообще поле переименовал в _text, а конструктор бы сделал по типу:
```
public LjPost(string text)
{}
```
А GetPost должен был бы быть, на мой взгляд, снаружи (например в каком-нибудь WebHelper) и в этот конструктор ты бы передавал уже текст поста, полученный через хелпер. 

Сейчас приду в личку и добьюсь от тебя, почему лучше так, а не как ты сделал

2022-10-07 12:25 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +using System.Collections.Generic;
Подчищай ненужные юзинги

2022-10-07 12:25 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +        private char[]? rawArray;
Ну про это мы поговорили. _camelCase не забудь

2022-10-07 12:25 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +        }
Всё же переделай в автосвойство. Это сэкономит строки кода и будет проще воспринимать информацию (как минимум, то, что передаваемое в свойство внутри класса значение доступно снаружи)

2022-10-07 12:25 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +            rawArray = new char[sr.BaseStream.Length];
А вообще зачем ты rawArray в поле вынес? Он же мог быть локальной переменной? Или ты ещё его как-то где-то использовать будешь?

2022-10-07 13:03 UTC, Jymapas commented on WeekChgkSPBParser/API/Connect.cs
>          internal ITelegramBotClient Bot = new TelegramBotClient(Constants.TgToken);
А, не туда посмотрел. Да, он нигде не используется, кроме Connect. Сделал приватным.

2022-10-07 13:04 UTC, Jymapas commented on WeekChgkSPBParser/API/LjPost.cs
> +        private string _post = GetPost();
Буду править, когда буду делать реализацию вытягивания из ЖЖ.

2022-10-07 13:14 UTC, Jymapas commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +            rawArray = new char[sr.BaseStream.Length];
пока думал про nullable, перемудрил. Верну в локальную переменную.

2022-10-08 14:11 UTC, merged