Feature/3 parse command
Jymapas/WeekChgkSPBParser pull request #7
Opened 2022-10-06 13:57 UTC by Jymapas

Пока что тригеррится на любой текст, отправляя в ответ готовый анонс из текстового файла.

2022-10-07 11:35 UTC, Jymapas commented on WeekChgkSPBParser/API/MessagesHandler.cs
> +            TxtPost _txtPost = new();
camelCase поправил, инициализацию оставлю как есть.

2022-10-07 13:00 UTC, FA72 requested changes
Лучше всё ж переделай. По стайлкоду проблем теперь вроде нет. Начинаю до сути доёбываться)

2022-10-07 13:00 UTC, FA72 commented on WeekChgkSPBParser/API/Connect.cs
> +        internal async void Start()
На кой тут тогда async?

2022-10-07 13:00 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +            get => _announcement;
Ну про автосвойство я в том ПРе писал. Я так понимаю, оно к этому ПР относится тоже. Так что тут переделай тоже, да

2022-10-07 13:00 UTC, FA72 commented on WeekChgkSPBParser/API/TxtPost.cs
> +            get => _anounce;
Опять. Зачем тут свойство и поле? Сделай 1 автосвойство и всё. С приватным сеттером

2022-10-07 13:00 UTC, FA72 commented on WeekChgkSPBParser/API/TxtPost.cs
>      internal class TxtPost
Лучше пускай тогда будет TxtPostReader тогда будет. Но всё равно. Он не должен, видимо, в себе содержать _announce или Announce сущность. Ты должен либо отдельный объект под него создать, либо textAnounce в соответствующем месте получать

2022-10-07 13:00 UTC, FA72 commented on WeekChgkSPBParser/API/TxtPost.cs
> +        public string Anounce
И да. Announce
Anounce - другое слово

2022-10-07 13:00 UTC, FA72 commented on WeekChgkSPBParser/API/TxtPost.cs
>              FileInfo file = new(Constants.Path);
Лучше принимать путь на вход в метод, чтобы универсальнее было

2022-10-07 13:00 UTC, FA72 commented on WeekChgkSPBParser/Constants.cs
>          internal const string Path = @"C:\\Users\petrakov_as\Desktop\anounsment.txt";
Путь до чего это? Назови лучше TxtAnnouncePath

2022-10-07 13:00 UTC, FA72 commented on WeekChgkSPBParser/API/MessagesHandler.cs
> +            Console.WriteLine(txtPost.Anounce);
Вот тут. Вместо того, чтобы инициализировать TxtPost было бы правильнее сделать так:
`string txtPost = TxtPostReader.GetAnnounce(Constant.TxtAnnouncePath) ;`
Это ещё хорошо тем, что тебе не надо каждый раз будет к какому-то свойству внутри какого-то объекта обращаться, а будешь работать непосредственно с стрингой

2022-10-07 13:59 UTC, FA72 commented
Вообще ПРки с конфликтами не смоторятся, если что. Так что мердж конфликты порешай) Заодно это научишься длеать

2022-10-09 14:51 UTC, Jymapas commented on WeekChgkSPBParser/API/TxtPost.cs
>      internal class TxtPost
Он ругался на лишний энтер в конце строки. Ааааа!

А где у меня по стайлу не камелКейс, а _камелКейс, где его быть не должно?

2022-10-10 05:35 UTC, FA72 requested changes

2022-10-10 05:35 UTC, FA72 commented on WeekChgkSPBParser/API/Connect.cs
> +        private ITelegramBotClient Bot = new TelegramBotClient(Constants.TgToken);
_camelCase. Установи решарпер, правда

2022-10-10 05:35 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +        private string _announcement;
убирай

2022-10-10 05:35 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +            _announcement = TgFormat(sr);
Announcement

2022-10-10 05:35 UTC, FA72 commented on WeekChgkSPBParser/API/TxtPostReader.cs
> +        public string Announce { get; private set; }
Опять двадцать пять. Убери _announce, правильно инициализируй Announce. Научись использовать автосвойства. Почитай, в конце-концов, что это. https://learn.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/auto-implemented-properties
https://metanit.com/sharp/tutorial/3.4.php - здесь чуть более понятно, может. 
Ну и да. про разделелние ответственности

2022-10-14 11:49 UTC, FA72 reviewed
Осталось совсем чуть-чуть комментов. Уже прям ГОРАЗДО лучше. Молодец

2022-10-14 11:49 UTC, FA72 commented on WeekChgkSPBParser/API/Connect.cs
> +            if (!string.Empty.Equals(Constants.TgToken))
А зачем это проверять? У тебя константа никогда не может быть пустой в нормальной работе приложения. Это бессмысленная проверка, кажется

2022-10-14 11:49 UTC, FA72 commented on WeekChgkSPBParser/API/LjPost.cs
> +        private static string GetPost()
Смотри. Если у тебя здесь будет работа с постом внутри этого метода (и пост LJ приватный и не будет никуда выдаваться наружу), то какой тебе смысл здесь делать статику? Это будет делаться в рамках экземпляра класса. А если переделывать, как я говорил (что есть отдельный LjPostHelper какой-то и какая-то сущность LjPost), то статик-метод нужен, но как раз в отдельном классе

2022-10-14 11:49 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +        internal TgHtmlFormat(string s)
Переменные должны иметь осмысленные названия. лучше, чтобы тут было что-то типа input или inputString

2022-10-14 11:49 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +            Match m = Regex.Match(s, @"(?<=(\n|<br\s?/?>))^[<b>][\w\W]+?(?=</p>)", RegexOptions.Multiline);
var match

2022-10-14 11:49 UTC, FA72 commented on WeekChgkSPBParser/API/TgHtmlFormat.cs
> +            Match m = Regex.Match(s, @"(?<=(\n|<br\s?/?>))^[<b>][\w\W]+?(?=</p>)", RegexOptions.Multiline);
Лучше в константы. Вообще в коде практически не должно быть никаких строк, передача которых идёт напрямую. Любой хардкод - плохо. Чтобы ты понимал почему - а если у тебя появится второй метод использующий эту регулярку? Ты её скопируешь. А потом ты вдруг решишь её поменять (ну там улучшить). Вот ты уже можешь случайно забыть в одном месте изменить и получить проблемы.

2022-10-14 11:49 UTC, FA72 commented on WeekChgkSPBParser/API/TxtPostReader.cs
> +            TgHtmlFormat t = new(streamReader.ReadToEnd());
имя лучше осмысленнее

2022-10-14 11:49 UTC, FA72 commented on WeekChgkSPBParser/Constants.cs
> +        internal static readonly string TgToken = GetFromTxt("TgToken.txt");
Подумай, что здесь неправильно сам, на основе уже бывших комментов и сделай правильно

2022-10-14 11:50 UTC, FA72 commented on WeekChgkSPBParser/API/Connect.cs
> +            if (!string.Empty.Equals(Constants.TgToken))
Понял. Удаляю

2022-10-14 13:50 UTC, FA72 requested changes
Последние, полагаю, замечания. Чисто по логике внутри классов, чтобы убрать всякие алогичные движения

2022-10-14 13:50 UTC, FA72 commented on WeekChgkSPBParser/API/Connect.cs
> +        private ITelegramBotClient _bot = new TelegramBotClient(GetFromTxtHelper.GetFromTxt(Constants.TgTokenPath));
Лучше вынеси это в метод Start. Инициализровать, используя методы при объявлении поля - довольно плохая практика

2022-10-14 13:50 UTC, FA72 commented on WeekChgkSPBParser/API/Connect.cs
> +            if (!string.Empty.Equals(GetFromTxtHelper.GetFromTxt(Constants.TgTokenPath)))
А если ты вынесешь в старт, ты ещё и сможешь завести локальную переменную под это значение и не дёргать два раза одно и то же из файла.

2022-10-14 13:50 UTC, FA72 commented on WeekChgkSPBParser/API/Connect.cs
> +            if (!string.Empty.Equals(GetFromTxtHelper.GetFromTxt(Constants.TgTokenPath)))
Ну и да. Для чего у тебя тут эта проверка тогда? инициализацию после неё сделай. И вообще лучше наоборот. проверяй на равенство string.Empty и если оно эмпти, то выдавай какой-то текст и вызывай ретёрн, так избавишься от лишней вложенности в иф.

2022-10-14 13:50 UTC, FA72 commented on WeekChgkSPBParser/API/TxtPostReader.cs
> +            TgHtmlFormat announcementText = new(GetFromTxtHelper.GetFromTxt(Constants.TxtAnnouncePath));
Не очень правильное название переменной. Это связано как раз с неправильным делением на классы. Вот тебя не смущает, что ты создаёшь какой-то TgHtmlFormat, который называется announcementText и ты из него достаёшь потом свойство Announcement? Ну то есть, если бы у тебя отдельно был класс Announcement со значением Text, то ты бы создал переменную announcement и обратившись к TgHtmlFormatter, какому-то методу класса, получил бы нужное значение и записал бы в это свойство? Оно же прям логичнее по структуре выглядит

2022-10-17 08:35 UTC, merged